name: Generate Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # 每天自动更新一次
  workflow_dispatch:             # 允许手动触发

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg              # 输出文件名，仓库根目录下
          user: ${{ github.repository_owner }} # 当前仓库拥有者
          token: ${{ secrets.METRICS_TOKEN }}   # 需要一个有 repo 权限的 PAT

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add metrics.svg
          git commit -m "chore: update metrics" || exit 0
          git push
